name: Build Android APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Web to APK
        uses: subhamk/web-to-apk-action@v1
        with:
          web-folder: "."
          app-name: "TMGame"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TMGame-APK
          path: "**/*.apk"
