name: Build Android APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build APK
        uses: kimhuilim/html-to-apk-action@v1
        with:
          build-folder-path: "."
          app-name: "TMGame"
          output-folder-path: "output/"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TMGame-APK
          path: output/*.apk
          
